{% load_yaml as lookup %}
Debian:
    repo_url: "deb https://packages.elastic.co/beats/apt stable main" 
    repo_file: /etc/apt/sources.list.d/beats.list
    gpg_url: "https://packages.elasticsearch.org/GPG-KEY-elasticsearch"
    package: filebeat
    service: filebeat
    config_file: /etc/filebeat/filebeat.yml
CentOS:
    repo_url: "https://packages.elastic.co/beats/yum/el/$basearch" 
    repo_file: /etc/yum.repos.d/beats.repo
    gpg_url: "https://packages.elasticsearch.org/GPG-KEY-elasticsearch"
    package: filebeat
    service: filebeat
    config_file: /etc/filebeat/filebeat.yml
{% endload %}

{% load_yaml as rawmap %}
hosts: localhost:5044
{% endload %}
